### ISSUE TITLE
Seg liver and tumor？

### ISSUE THREAD

**Issue by NBIronman** [zz10001/LITS_3d#1]
Hello, can this code be able to segment liver and tumor at the same time?

**Comment by zz10001** [comment]
Of course, it could be.

**Comment by NBIronman** [comment]
> Of course, it could be.

Hello, is it convenient to give me your WeChat? I am using your code and encountered some problems and would like to ask you

**Comment by zz10001** [comment]
Sorry, I'm afraid not, I am busy now.

**Comment by NBIronman** [comment]
> Sorry, I'm afraid not, I am busy now.

OK,Thank you

**Comment by NBIronman** [comment]
I found that you did not provide the test code for the 3D version. Does your 2D version match the 3D version?
