### ISSUE TITLE
I found that you did not provide the test code for the 3D version. Does your 2D version match the 3D version?

### ISSUE THREAD

**Issue by NBIronman** [zz10001/LITS_3d#2]
Hello，I found that you did not provide the test code for the 3D version. Does your 2D version match the 3D version?

**Comment by zz10001** [comment]
There is a difference, You need to make patch(`64*128*160`) to a whole volume(`z*512*512`), And it has some bug to fix, You can try it by yourself.maybe it can be useful to you according to this [repo](https://github.com/lee-zq/3DUNet-Pytorch/blob/master/dataset/dataset_lits_test.py)
