### ISSUE TITLE
I tried to use your code and tumor prediction is very bad. Training  dice score was 90+ but during test it shows very bad results. Can you share share your trained model on tumor so I can check the inference?

### ISSUE THREAD

**Issue by Abbas009** [zz10001/LITS_3d#3]

**Comment by zz10001** [comment]
Sorry, I did not save the previous model, How many epochs did you train? maybe You can try to train 150+ epochs, By the way, Have you changed anything？ and it has some bug on [here](https://github.com/zz10001/LITS2017-main2/blob/a16c7a1ff10dd19bd7b422ed87d6a6a534940ef4/data_prepare/preprocess.py#L126), it should have a judge the difference of ct_array.shape[0] and blockz when ct_array.shape[0]<blockz + numz. you can fix it by yourself. Good luck!
