### ISSUE TITLE
取训练集与验证集时的问题

### ISSUE THREAD

**Issue by Jiangj512** [zz10001/LITS_3d#4]
train_img_paths, val_img_paths, train_mask_paths, val_mask_paths = train_test_split(img_paths, mask_paths, test_size=0.3, random_state=39)
这样取训练集与验证集不会导致有交叉吗，来自同一个ct的不同切块同时被分到训练集与验证集中。

**Comment by zz10001** [comment]
会，所以训练时候验证集的指标会很高，你可以尝试下处理这个问题，项目不在维护了
