### ISSUE TITLE
这位是你吗

### ISSUE THREAD

**Issue by A1ANGithub** [zz10001/LITS_3d#5]
38 | zz1 | 10 | 05/08/21 | 0.6610 (69) | 0.8060 (38) | 0.350 (30) | -0.033 (121) | 0.995 (37) | 6.270 (64) | 1.505 (38) | 0.393 (56) | 0.360 (86)

**Comment by zz10001** [comment]
> 38 | zz1 | 10 | 05/08/21 | 0.6610 (69) | 0.8060 (38) | 0.350 (30) | -0.033 (121) | 0.995 (37) | 6.270 (64) | 1.505 (38) | 0.393 (56) | 0.360 (86)

是的。
