### ISSUE TITLE
您好，问下Score of Test Set from LiTS website中的结果是哪个net训练得到的结果？

### ISSUE THREAD

**Issue by Oct6ber** [zz10001/LITS_3d#6]

**Comment by zz10001** [comment]
应该就是unet3d，不过有点忘了是已经上传了的还是后面改了的版本，这个应该是最初的版本，后面好像改了一点模型保存的策略和预测时候滑块的步长，具体改了哪些有点忘了，不过这个有点太耗时了，我用了3个2080ti跑了3天多才得到的这个结果，数据处理的方式和训练的策略应该改下比较好
